### ISSUE TITLE
Install as a git submodule (Improvement)

### ISSUE THREAD

**Issue by NagyWesley** [marefati110/strapi-plugin-elastic#13]
(Improvement not a bug) strapi-plugin-elastic should be used as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Please update the Readme to follow it.

**Comment by globalsysgabriell** [comment]
@NagyWesley https://github.com/marefati110/strapi-plugin-elastic/pull/20 😌
