### ISSUE TITLE
Error: The model articles can't be found

### ISSUE THREAD

**Issue by sandiprb** [marefati110/strapi-plugin-elastic#14]
Configuration as below:

```
{
  connection: {
    node: env("ELASTICSEARCH_HOST", "http://127.0.0.1:9200/"),
    auth: {
      username: env("ELASTICSEARCH_USERNAME"),
      password: env("ELASTICSEARCH_PASSWORD"),
    },
  },

  setting: {
    version: 1,
    validStatus: [200, 201],
    validMethod: ["PUT", "POST", "DELETE"],
    fillByResponse: false,
    importLimit: 3000,
    index_prefix: "",
    index_postfix: "",
    removeExistIndexForMigration: false,
  },
  models: [
    {
      model: "articles",
      pk: "id",
      plugin: true, // changed to true
      enable: true,
      index: "articles",
      relations: [],
      conditions: {},
      supportAdminPanel: true,
      fillByResponse: true,
      migration: true,
      urls: [],
    },
  ],
}
```

The Elastic Search admin panel also appears blank and while clicked on migrate it throws error 500
Screenshots below:

<img width="1194" alt="1" src="https://user-images.githubusercontent.com/18263041/104431977-893bcc00-55ae-11eb-896c-01f0cd232a43.png">

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/18263041/104431988-8b9e2600-55ae-11eb-87d7-e10c2764be29.png">

<img width="662" alt="3" src="https://user-images.githubusercontent.com/18263041/104431999-8e991680-55ae-11eb-8bf6-8a003177b1b7.png">

**Comment by marefati110** [comment]
@sandiprb 
Can you change plugin prop to false and test again

**Comment by sandiprb** [comment]
That worked @marefati110 
Thanks a lot!!

**Comment by TheMangoTrain** [comment]
> @sandiprb
> Can you change plugin prop to false and test again

This worked for me as well.
