### ISSUE TITLE
Cannot see plugin in admin dashboard

### ISSUE THREAD

**Issue by TheMangoTrain** [marefati110/strapi-plugin-elastic#15]
Hello,

I have this plugin installed, and after some wrestling I did get it to a point where data was being indexed in elasticsearch and ultimately, as a test, pulled the data into an external client via API. **Thank you for this plugin!**

However, up to now I have never seen this plugin appear in the Strapi admin dashboard sidebar. I see it in screenshots (examples: [Link1](https://github.com/marefati110/strapi-plugin-elastic), [Link2](https://github.com/marefati110/strapi-plugin-elastic/issues/14)), so presumably it exists? I do see this plugin appear in the Strapi settings/roles area, where you setup permissions. I set each permission to `isAuthenticated`.

As a final test, did everything over again in a clean test install of Strapi and your plugin, and still do not see it in the Strapi admin dashboard.

I'm not sure what obvious thing I may be missing beyond your install instructions.

On this note, I see two different installations of this plugin... [LinkA](https://github.com/marefati110/strapi-plugin-elastic) and [LinkB](https://www.npmjs.com/package/strapi-plugin-elastic), with different instructions. Which is the real thing?

Here's some of my important details:

**myproject/config/elasticsearch.js**

```
module.exports = ({ env }) => ({
  connection: {
    // https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html
    node: env('ELASTICSEARCH_HOST', 'http://127.0.0.1:9200'),
  },
  setting: {
    validStatus: [200, 201],
    validMethod: ['PUT', 'POST', 'DELETE'],
    importLimit: 3000,
    index_postfix: '',
    index_postfix: '',
    removeExistIndexForMigration: false,
  },
  models: [
  {
    "model": ".gitkeep",
    "index": ".gitkeep",
    "plugin": null,
    "enable": false,
    "migration": false,
    "pk": "id",
    "relations": [],
    "conditions": {},
    "fillByResponse": true,
    "supportAdminPanel": true,
    "urls": []
  },
  {
    "model": "my-content-type",
    "index": "my-content-type",
    "plugin": true,
    "enable": true,
    "migration": true,
    "pk": "id",
    "relations": [],
    "conditions": {},
    "fillByResponse": true,
    "supportAdminPanel": true,
    "urls": []
  }
]
});
```

**my-project/config/middleware.js**

```
module.exports = {
    load: {
      before: ['responseTime', 'logger', 'cors', 'responses', 'elastic'],
      order: [
        
      ],
      after: ['parser', 'router'],
    },
    settings: {
        elastic: {
            enabled: true
        }
    }
}
```

**my-project/config/cron.js:**

```
const moment = require('moment');
module.exports = {
  '*/10 * * * *': async () => {
    const updateTime = moment()
      .subtract(10, 'minutes')
      .format('YYYY-MM-DD HH:mm:ss');

    // currentTime
    await strapi.elastic.migrateModels({
      conditions: { updated_at_gt: updateTime },
    });
  }
}
```

**Comment by marefati110** [comment]
@TheMangoTrain  Thanks :D

- to see plugin in admin sidebar use `yarn build --clean` and test it again
- in `myproject/config/elasticsearch.js` change plugin prob to false
- and set permisson just for admin role

**Comment by marefati110** [comment]
i will update documents

**Comment by marefati110** [comment]
`".gitkeep"` model is a bug and you can remove it

**Comment by TheMangoTrain** [comment]
Hey many thanks for the quick response!
It was `yarn build --clean` which was needed to prepare the admin area.

Presumably, going forward we'd only have to run `build` once in awhile (ie if this plugin has an update) ?

**Comment by marefati110** [comment]
@TheMangoTrain 

every one the ui in plugin changed need to use yarn build --clean
