### ISSUE TITLE
Use plugin only to fetch data

### ISSUE THREAD

**Issue by anthmarques** [marefati110/strapi-plugin-elastic#17]
This is not a bug, its a single question.

Is it possible to use the plugin only to fetchAll/fetchById documents of a collection?

Thanks in advance.

**Comment by marefati110** [comment]
hi @anthmarques 
to fetchById can use 
https://github.com/marefati110/strapi-plugin-elastic#findone-
or 
`const article = strapi.elastic.get({ index: 'article', id: 1 })`

or you can use 
`strapi.elastic.search(....)`
official elasticsearch api

 https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html
