### ISSUE TITLE
Error 404: /strapi-plugin-elastic/models Not Found

### ISSUE THREAD

**Issue by nazrighazi** [marefati110/strapi-plugin-elastic#9]
I tried to use the plugin in strapi v3.2.4, but seems like there's an error 404, saying that localhost:1337/strapi-plugin-elastic/models not found. Is there anything that i missed out? I already added configuration in middleware.js and set plugin and enable in elasticsearch.js to true.

My middleware.js
![middleware2](https://user-images.githubusercontent.com/32353602/99387391-df71f300-290e-11eb-86c5-1687a4b6d1ef.PNG)

my elasticsearch.js
![middleware](https://user-images.githubusercontent.com/32353602/99387406-e6006a80-290e-11eb-8ec1-2db83b79809b.PNG)

I start the strapi and the elasticsearch plugin displayed but there is no models in it. I looked in the console and saw the 404 error.
![strapi](https://user-images.githubusercontent.com/32353602/99387580-34156e00-290f-11eb-816d-3ce7094a3cf1.PNG)

![Capture2](https://user-images.githubusercontent.com/32353602/99387853-9b332280-290f-11eb-8048-990911fe2107.PNG)

**Comment by marefati110** [comment]
hi @nazrighazi
thanks for your reporting
do uou change `strapi-plugin-elastic` folder name ?

**Comment by nazrighazi** [comment]
hi @marefati110. Just realized that. now it's working. Thank you.
